/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();

        // Setear un icono
        Image imageIcon = new ImageIcon("src/imagenes/java.png").getImage();
        this.setIconImage(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMostrarModal = new javax.swing.JButton();
        buttonMostrarNoModal = new javax.swing.JButton();
        textMensaje = new javax.swing.JTextField();
        buttonMostrarMensaje = new javax.swing.JButton();
        buttonPedirMensaje = new javax.swing.JButton();
        buttonMostrarConfirmacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 800));

        buttonMostrarModal.setText("Mostrar Modal");
        buttonMostrarModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarModalActionPerformed(evt);
            }
        });

        buttonMostrarNoModal.setText("Mostrar No Modal");
        buttonMostrarNoModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarNoModalActionPerformed(evt);
            }
        });

        buttonMostrarMensaje.setText("Mostrar Mensaje");
        buttonMostrarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarMensajeActionPerformed(evt);
            }
        });

        buttonPedirMensaje.setText("Pedir Mensaje");
        buttonPedirMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPedirMensajeActionPerformed(evt);
            }
        });

        buttonMostrarConfirmacion.setText("Mostrar Confirmacion");
        buttonMostrarConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarConfirmacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMensaje)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonMostrarModal)
                                .addGap(18, 18, 18)
                                .addComponent(buttonMostrarNoModal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonMostrarMensaje)
                                .addGap(18, 18, 18)
                                .addComponent(buttonPedirMensaje)
                                .addGap(18, 18, 18)
                                .addComponent(buttonMostrarConfirmacion)))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMostrarMensaje)
                    .addComponent(buttonPedirMensaje)
                    .addComponent(buttonMostrarConfirmacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMostrarModal)
                    .addComponent(buttonMostrarNoModal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMostrarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarModalActionPerformed
        DialogModal dialogModal = new DialogModal(this, true);
        
        dialogModal.setLocationRelativeTo(null); 
        dialogModal.setVisible(true);                
    }//GEN-LAST:event_buttonMostrarModalActionPerformed

    private void buttonMostrarNoModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarNoModalActionPerformed
        FrameNoModal frameNoModal = new FrameNoModal();
        
        frameNoModal.setLocationRelativeTo(null); 
        frameNoModal.setVisible(true);    
    }//GEN-LAST:event_buttonMostrarNoModalActionPerformed

    private void buttonMostrarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarMensajeActionPerformed
        JOptionPane.showMessageDialog(this, textMensaje.getText(), "Titulo del JOptionPane", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonMostrarMensajeActionPerformed

    private void buttonPedirMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPedirMensajeActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Como te llamas?");
        
        textMensaje.setText(nombre);
    }//GEN-LAST:event_buttonPedirMensajeActionPerformed

    private void buttonMostrarConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarConfirmacionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea formatear esta computadora?", "Titulo del JOptionPane", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Elegiste si", "Titulo del JOptionPane", JOptionPane.INFORMATION_MESSAGE);
        }      
    }//GEN-LAST:event_buttonMostrarConfirmacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMostrarConfirmacion;
    private javax.swing.JButton buttonMostrarMensaje;
    private javax.swing.JButton buttonMostrarModal;
    private javax.swing.JButton buttonMostrarNoModal;
    private javax.swing.JButton buttonPedirMensaje;
    private javax.swing.JTextField textMensaje;
    // End of variables declaration//GEN-END:variables
}
