/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p111mil.agenda.formularios;

import java.text.NumberFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import p111mil.agenda.modelo.Ciudad;
import p111mil.agenda.dao.CiudadDao;
import p111mil.agenda.dao.ContactoDao;
import p111mil.agenda.modelo.Contacto;

/**
 *
 * @author PC-MAESTRO
 */
public class Edicion extends javax.swing.JFrame {
    private Listado listado;
    
    public void mostrarFormulario(Listado listado) {
        this.listado = listado;        
        this.listado.setEnabled(false);
        
        this.setLocationRelativeTo(listado);
        this.setVisible(true);        
    }
    
    public void cerrarFormulario() {
        this.dispose();
        this.listado.setVisible(true);
        this.listado.setEnabled(true);
    }
    
    private void limpiarFormulario() {
        this.textoNombre.setText("");
        this.textoApellido.setText("");
        this.textoTelefono.setText("");
        this.comboCiudades.setSelectedIndex(0);        
    }
    
    /**
     * Creates new form Edicion
     */
    public Edicion() {
        initComponents();
        
        // Para evitar hacer copy/paste sobre los campos
        textoNombre.setTransferHandler(null);
        textoApellido.setTransferHandler(null);
        textoTelefono.setTransferHandler(null);
        
        CiudadDao ciudadDao = new CiudadDao();
        List<Ciudad> ciudades = ciudadDao.buscarTodos();
        
        comboCiudades.setModel(new DefaultComboBoxModel(ciudades.toArray()));
        comboCiudades.setSelectedIndex(0);
        
        limpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoApellido = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        labelNombre2 = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        comboCiudades = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edicion de Contacto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelNombre.setText("Nombre");

        textoNombre.setText("Nombre");
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });

        textoApellido.setText("Apellido");
        textoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoApellidoKeyTyped(evt);
            }
        });

        labelApellido.setText("Apellido");

        textoTelefono.setText("Telefono");
        textoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTelefonoKeyTyped(evt);
            }
        });

        labelNombre2.setText("Teléfono");

        labelCiudad.setText("Ciudad");

        comboCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelNombre2)
                            .addComponent(labelApellido)
                            .addComponent(labelCiudad))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoApellido)
                    .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboCiudades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.cerrarFormulario();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.listado.setVisible(true);
        this.listado.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // 1. Validamos que todos los datos sean validos
        if (textoNombre.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El Nombre es obligatorio", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Nombre
            textoNombre.requestFocus();
            return;
        }
        
        if (textoApellido.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El Apellido es obligatorio", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Apellido
            textoApellido.requestFocus();
            return;
        }
        
        if (textoTelefono.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El Telefono es obligatorio", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Telefono
            textoTelefono.requestFocus();
            return;
        }
        
        if (textoNombre.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "La longitud del Nombre no puede ser mayor a 50 caracteres", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Telefono
            textoNombre.requestFocus();
            return;
        }
        
        if (textoApellido.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "La longitud del Apellido no puede ser mayor a 50 caracteres", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Telefono
            textoApellido.requestFocus();
            return;
        }        
                        
        if (textoTelefono.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "La longitud del Telefono no puede ser mayor a 50 caracteres", "Edicion de Contacto", JOptionPane.INFORMATION_MESSAGE);
            // Seteo el cursor sobre el campo Telefono
            textoNombre.requestFocus();
            return;
        }
        
        // 2. Guardamos en la base de datos
        Contacto contacto = new Contacto();
        
        contacto.setNombre(textoNombre.getText());
        contacto.setApellido(textoApellido.getText());
        contacto.setTelefono(textoTelefono.getText());
        contacto.setCiudad((Ciudad) comboCiudades.getSelectedItem());
        
        ContactoDao contactoDao = new ContactoDao();
        contactoDao.guardar(contacto);
        
        // 3. Cerramos el formulario y refrescamos la base de datos
        this.cerrarFormulario();        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        if (textoNombre.getText().length() >= 50) {
            // Si ya llegue a los 5 caracteres el consume() hace que de ahora en mas las teclas no agreguen mas caracteres
            evt.consume();
        }
    }//GEN-LAST:event_textoNombreKeyTyped

    private void textoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoApellidoKeyTyped
        if (textoApellido.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_textoApellidoKeyTyped

    private void textoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTelefonoKeyTyped
        if (textoTelefono.getText().length() >= 50) {
            evt.consume();
        } else {        
            char caracter = evt.getKeyChar();

            // Verificar si la tecla pulsada no es un digito
            // Caracteres validos: 0123456789 +#*
            if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != '+') &&
                (caracter != '#') &&
                (caracter != '*') &&
                (caracter != '\b')) /* corresponde a BACK_SPACE */
            {
                evt.consume();  // ignorar el evento de teclado
            }
        }               
    }//GEN-LAST:event_textoTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> comboCiudades;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
